# Generated by Django 3.0.5 on 2020-04-05 04:56

from django.db import migrations, models


class Migration(migrations.Migration):
	initial = True

	dependencies = [
	]

	operations = [
		migrations.CreateModel(
			name='Song',
			fields=[
				('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
				('duration', models.IntegerField(default=0, editable=False, verbose_name='Song duration (ms)')),
				('title', models.CharField(max_length=100, verbose_name='Title')),
				('artist', models.CharField(blank=True, max_length=100, verbose_name='Artist')),
				('album', models.CharField(blank=True, max_length=100, verbose_name='Album name')),
				('track_number', models.SmallIntegerField(blank=True, null=True, verbose_name='Track number')),
				('genre', models.CharField(blank=True, max_length=50, verbose_name='Genre')),
				('year', models.CharField(blank=True, max_length=4, verbose_name='Year')),
				('publisher', models.CharField(blank=True, max_length=100, verbose_name='Publisher')),
				('cover_image', models.ImageField(default='playlistAPI/static/assets/default_song_img.jpg',
				                                  upload_to='playlistAPI/static/assets', verbose_name='Cover image')),
				('added_date', models.DateTimeField(auto_now_add=True)),
			],
			options={
				'db_table': 'songs',
			},
		),
		migrations.CreateModel(
			name='songsByPlatform',
			fields=[
				('added_date', models.DateTimeField(auto_now_add=True)),
				('songID', models.IntegerField(primary_key=True, serialize=False)),
				('spotifyID', models.TextField(blank=True)),
				('appleID', models.TextField(blank=True)),
				('youtubeID', models.TextField(blank=True)),
			],
			options={
				'db_table': 'songs_by_platform',
			},
		),
	]
